### ISSUE TITLE
Trouble parsing msgpack input, falling back to plain text ??

### ISSUE THREAD

**Issue by fbacchella** [logstash-plugins/logstash-codec-msgpack#4]
This comportement is very strange.

If a encoded packed in msgpack format failed to decode, it will probably not be decoded as text. There is nothing else to do than discard it.

**Comment by kares** [comment]
thanks for the report, the plugin improved it's decoding logic in https://github.com/logstash-plugins/logstash-codec-msgpack/pull/13 to generate a fallback event (like other codecs do)
